### PR TITLE
Test

### PR DESCRIPTION
**Pull request by marcosmerida**
Hi! I am Juan, the creator of this project.

In order to describe with details all the things that I learned with this project, I'll write a small list with a summary.

Create fixed navbars.
Clean interface with Grid, display:flex/block.
About the properties and differences of a link, a paragraph and a span in HTML
About the good use for the element.
How to place and move elements with Grid CSS.
How to use fonts from a website in my project.
How to put a cool style in buttons and links.
With the linterns i have an idea about how to organize my future projects to make an easier review.
Fix the issue between a lintern and a json file in the file of the project.

I really enjoyed workin on this project!

### CODE REVIEW

**Review by eypsrcnuygr — COMMENTED** [review]
## Status: Invalid Submission :stop_sign: 

Hello @marcosmerida. I'm invalidating your PR because it doesn't pass the linter checks. And due to [this rule](https://microverse.zendesk.com/hc/en-us/articles/1500002085202-February-2nd-2021-linter-errors-as-a-reason-of-project-invalidation-), I should invalidate it. Please take linters into consideration in your next submissions. 

Have a nice day!
_Eyüp Sercan UYGUR_

**Review by voscarmv — CHANGES_REQUESTED** [review]
Hi @marcosmerida ,

As the previous Code Reviewer mentioned, your GitHub Actions tests are failing. Mainly, you have a series of CSS linter errors. Because of this, I will have to invalidate your submission yet once again. But don't worry:

You can use the `npx stylelint "**/*.{css,scss}" --fix` command in your local environment to automatically fix these errors before submitting again. Please read the instructions here to learn more about how to do this: https://github.com/microverseinc/linters-config/tree/master/html-css

If you need any help feel free to contact me on Slack, my handle is Oscar Mier.
Cheers and Happy Coding!

**Comment by marcosmerida** [comment]
Hi Oscar! Nice to meet you.

In this case i already used the npx stylelint "**/*.{css,scss}" -- in my
local console, fixed all the errors and then i did the pull request, but in
the lintern said that i have errors that i already fixed, i even went to my
code and there's nothing where it says i have an error, is there any way to
fix it?

i really appreciate your quick response and the time you took to give me an
answer by the way

**Review by voscarmv — CHANGES_REQUESTED** [review]
# Impressive work.  💻 👀 ✨
- Excellent work with replicating the original page. The page design looks fantastic and very closely resembles the original.
- Good work fixing the linter errors.

## However, there are some changes required 👀 🧰 🔨 🔧
Your project is very complete. However, your Pull Request description and your README file are very unprofessional. These are reasons for invalidating a project, but I'll make a judgement call here and allow you to make these changes for your following code review since you've already received so many invalidations before and I would not want to hinder your progress in the curriculum. But please, do remember to fix this issues before you submit again! Other code reviewers might not me as understanding in your future projects 😃 

- Please use one of the README templates provided by Microverse on the project requirements. Your README is supposed to contain multiple sections, like a more detailed description of the tools used, a section describing the Licensing of your project, author's contact information, etcetera.
- Also please provide a well-detailed Pull Request description that contains a thorough list of all the things you learned and applied in building this project.

***[OPTIONAL]***
- You may use `<aside>` to add the Editor's Picks section from the original page design:
image
- You may use absolute positioning for the editor's picks and subscribe sections. The expected outcome can be achieved way more easily with the use of the `<section>` and `<aside>` tags which help keep the document flow.
- You may add a sticky footer like the one from the original page design as well.

**Remember**, you only have 3 opportunities to apply changes to this project in order to get it approved. Please apply the changes required in this code review, but also, make sure to go through the original project description to increase your chances of success in the next code review!

### Submit these changes and request a new code review! 😄 👍

### Questions or comments? Reach me on [Twitter](https://twitter.com/voscarmv) or [LinkedIn](https://linkedin.com/in/oscar-mier)🧑‍💻🗨️🧑‍💻
# Happy Coding! 🧠 ⌨️ 🖱️ 🖥️

**Comment by marcosmerida** [comment]
Hi! I am Juan, the creator of this project.

In order to describe with details all the things that I learned with this project, I'll write a small list with a resume.

- Create fixed navbars.
- Clean interface with Grid, display:flex/block.
- About the properties and differences of a link, a paragraph and a span in HTML
- About the good use for the <section> element.
- How to place and move elements with Grid CSS.
- How to use fonts from a website in my project.
- How to put a cool style in buttons and links.
- With the linterns i have an idea about how to organize my future projects to make an easier review.
- Fix the issue between a lintern and a json file in the file of the project.

I really enjoyed workin on this project!

**Review by Temmarie — CHANGES_REQUESTED** [review]
## Changes Required! :recycle:

### Hi @marcosmerida        ! :wave: :wave:

#### You have done well implementing most of the previously required changes. Your project looks amazing and almost the same as the original. I really enjoyed reviewing it.  :clap: However, there are changes required for you to make in order for this project to be approved. **_Note that you have one more review on this project in accordance with the [Code Reviews Limit Policy](https://microverse.zendesk.com/hc/en-us/restricted?return_to=https%3A%2F%2Fmicroverse.zendesk.com%2Fhc%2Fen-us%2Farticles%2F1500004088561), so make all of the required changes before submitting for a review._**
- - -

### **Recommended**

**General**
- [ ] Normalize the use of semantic HTML tags. See [here](https://www.w3schools.com/html/html5_semantic_elements.asp) for more information.

**Section Specific requirements**
- [ ] There are a couple of sections that are missing in your page, which includes: 

- The Editors' Picks sidebar. It can be added using an `aside` tag.
**Original**
Screenshot (123).
- The Most Popular section.
**Original**
Screenshot (87)

- Footer, this section is missing the icons. Checkout [font awesome](https://fontawesome.com/v4.7.0/icons/) for them.

__ As I said earlier, you have one more review before you reach the code review limit, so kindly make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink:
__Grace Tamara Ekunola __
[GitHub](https://github.com/temmarie) | [LinkedIn](https://www.linkedin.com/in/ekunola-grace/) | [Twitter](https://twitter.com/TemmarieW)

**Pull request closed without merging**
